_target_: src.dataset_module.ice_text_image_iclm_ds.ICETextImageICLMDataset


clip_processor_name: ${train.iclm_model.clip_name}
index_set_length: ${dataset.train_ds_len}

query_image_field: ${task.image_field}
query_text_field: ${task.query_text_feature_field}
ice_image_field: ${task.image_field}
ice_text_field: ${task.ice_text_feature_field}